name: Build
on: [push]

jobs:
 build:
   runs-on: ubuntu-latest
   name: A job to build resume
   steps:
   - name: Checkout
     uses: actions/checkout@v2
   - name: Build resume
     id: build
     uses: ./
